### ISSUE TITLE
Typo in gauss2D function

### ISSUE THREAD

**Issue by ttgump** [skolouri/swgmm#1]
Hi,
I am reading your code. In line 53 of utils.py, it says:

`P = np.linalg.det(Sigma) ** -.5 ** (2 * np.pi) ** (-X.shape[1]/2.)`

I guess it should be

`P = np.linalg.det(Sigma) ** -.5 * (2 * np.pi) ** (-X.shape[1]/2.)`

Since the function "gauss2D" is supposed to calculate the probability of the Gaussian distribution. Thanks.
Best,
Tian Tian

**Comment by skolouri** [comment]
Thank you! It is fixed.
